DROP SCHEMA IF EXISTS insurance CASCADE;

-- It merges the enterprise normalized design (Phase 2) with the full suite of 
-- Bi-Temporal, Versioning, and Auditing columns.
-- 
-- All active tables have DEFAULT values for the new columns to ensure 100% 
-- backward compatibility with existing legacy INSERT statements.

CREATE SCHEMA IF NOT EXISTS insurance;
SET search_path TO insurance;

CREATE TABLE insurance.company_branch (
    branch_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_count INT NOT NULL CHECK (employee_count >= 0),
    city VARCHAR(100),
    zipcode VARCHAR(20),
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert'
);

CREATE TABLE insurance.company_branch_history (LIKE insurance.company_branch);
ALTER TABLE insurance.company_branch_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

CREATE TABLE insurance.agent (
    agent_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    city VARCHAR(100),
    zipcode VARCHAR(20),
    branch_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_agent_branch FOREIGN KEY (branch_id) 
        REFERENCES insurance.company_branch(branch_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.agent_history (LIKE insurance.agent);
ALTER TABLE insurance.agent_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 3. CUSTOMER
CREATE TABLE insurance.customer (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth DATE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    city VARCHAR(100),
    zipcode VARCHAR(20),
    agent_id INT,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_customer_agent FOREIGN KEY (agent_id) 
        REFERENCES insurance.agent(agent_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.customer_history (LIKE insurance.customer);
ALTER TABLE insurance.customer_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 4. POLICY
CREATE TABLE insurance.policy (
    policy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    premium NUMERIC(12, 2) NOT NULL CHECK (premium >= 0),
    coverage NUMERIC(12, 2) NOT NULL CHECK (coverage >= 0),
    branch_id INT NOT NULL,
    agent_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_policy_branch FOREIGN KEY (branch_id) 
        REFERENCES insurance.company_branch(branch_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_policy_agent FOREIGN KEY (agent_id) 
        REFERENCES insurance.agent(agent_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_policy_dates CHECK (end_date >= start_date)
);

CREATE TABLE insurance.policy_history (LIKE insurance.policy);
ALTER TABLE insurance.policy_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 5. PAYMENT
CREATE TABLE insurance.payment (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    customer_id INT NOT NULL,
    policy_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_payment_customer FOREIGN KEY (customer_id) 
        REFERENCES insurance.customer(customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_payment_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.payment_history (LIKE insurance.payment);
ALTER TABLE insurance.payment_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 6. CLAIM
CREATE TABLE insurance.claim (
    claim_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount_issued NUMERIC(12, 2) NOT NULL CHECK (amount_issued >= 0),
    date_issued DATE NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert'
);

CREATE TABLE insurance.claim_history (LIKE insurance.claim);
ALTER TABLE insurance.claim_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 7. HEALTH POLICY DETAIL
CREATE TABLE insurance.health_policy_detail (
    health_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_history TEXT,
    associated_hospital VARCHAR(255),
    treatment_not_insured TEXT,
    policy_id INT NOT NULL UNIQUE,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_health_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.health_policy_detail_history (LIKE insurance.health_policy_detail);
ALTER TABLE insurance.health_policy_detail_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 8. CAR POLICY DETAIL
CREATE TABLE insurance.car_policy_detail (
    car_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    registration_year INT NOT NULL,
    policy_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_car_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.car_policy_detail_history (LIKE insurance.car_policy_detail);
ALTER TABLE insurance.car_policy_detail_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 9. HOME POLICY DETAIL
CREATE TABLE insurance.home_policy_detail (
    home_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_type VARCHAR(100),
    city VARCHAR(100),
    zipcode VARCHAR(20),
    year_built INT,
    area_sq_ft INT,
    policy_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    CONSTRAINT fk_home_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.home_policy_detail_history (LIKE insurance.home_policy_detail);
ALTER TABLE insurance.home_policy_detail_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 10. BRIDGE TABLES (Customer_Policy, Claim_Policy)
CREATE TABLE insurance.customer_policy (
    customer_id INT NOT NULL,
    policy_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    PRIMARY KEY (customer_id, policy_id),
    CONSTRAINT fk_cp_customer FOREIGN KEY (customer_id) 
        REFERENCES insurance.customer(customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cp_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.customer_policy_history (LIKE insurance.customer_policy);
ALTER TABLE insurance.customer_policy_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

CREATE TABLE insurance.claim_policy (
    claim_id INT NOT NULL,
    policy_id INT NOT NULL,
    
    -- Temporal & Audit Columns
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    transaction_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_to TIMESTAMP NOT NULL DEFAULT '9999-12-31 23:59:59',
    version_number INT NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    modified_by VARCHAR(255) NOT NULL DEFAULT CURRENT_USER,
    change_reason TEXT NOT NULL DEFAULT 'Initial Insert',

    PRIMARY KEY (claim_id, policy_id),
    CONSTRAINT fk_clp_claim FOREIGN KEY (claim_id) 
        REFERENCES insurance.claim(claim_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_clp_policy FOREIGN KEY (policy_id) 
        REFERENCES insurance.policy(policy_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE insurance.claim_policy_history (LIKE insurance.claim_policy);
ALTER TABLE insurance.claim_policy_history ADD COLUMN history_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;

-- 11. TRIGGERS
CREATE OR REPLACE FUNCTION insurance.payment_check_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  prem NUMERIC(12,2);
BEGIN
  SELECT premium INTO prem 
  FROM insurance.policy 
  WHERE policy_id = NEW.policy_id;
  
  IF NEW.amount < prem THEN
    RAISE EXCEPTION 'Payment amount (%) is less than the required premium (%)', NEW.amount, prem;
  ELSIF NEW.amount > prem THEN
    RAISE EXCEPTION 'Payment amount (%) is more than the required premium (%)', NEW.amount, prem;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payment_check ON insurance.payment;

CREATE TRIGGER payment_check
BEFORE INSERT OR UPDATE ON insurance.payment
FOR EACH ROW
EXECUTE FUNCTION insurance.payment_check_fn();

-- of records by applying Foreign Key B-Tree indexes, Composite Versioning indexes,
-- and highly advanced GiST (Generalized Search Tree) temporal indexes.

SET search_path TO insurance;

-- Required to combine standard columns (like customer_id) with range types 
-- (like tsrange) within a single GiST index.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- PostgreSQL does not automatically index foreign keys. Without these, JOINs 
-- and cascading validations will trigger full table scans.

CREATE INDEX idx_agent_branch ON insurance.agent(branch_id);
CREATE INDEX idx_customer_agent ON insurance.customer(agent_id);
CREATE INDEX idx_policy_branch ON insurance.policy(branch_id);
CREATE INDEX idx_policy_agent ON insurance.policy(agent_id);
CREATE INDEX idx_payment_customer ON insurance.payment(customer_id);
CREATE INDEX idx_payment_policy ON insurance.payment(policy_id);
CREATE INDEX idx_health_policy ON insurance.health_policy_detail(policy_id);
CREATE INDEX idx_car_policy ON insurance.car_policy_detail(policy_id);
CREATE INDEX idx_home_policy ON insurance.home_policy_detail(policy_id);

-- 3. HISTORY TABLES: COMPOSITE SORTING INDEXES
-- record ordered by its version.

CREATE INDEX idx_hist_branch_sort ON insurance.company_branch_history(branch_id, version_number);
CREATE INDEX idx_hist_agent_sort ON insurance.agent_history(agent_id, version_number);
CREATE INDEX idx_hist_customer_sort ON insurance.customer_history(customer_id, version_number);
CREATE INDEX idx_hist_policy_sort ON insurance.policy_history(policy_id, version_number);
CREATE INDEX idx_hist_payment_sort ON insurance.payment_history(payment_id, version_number);
CREATE INDEX idx_hist_claim_sort ON insurance.claim_history(claim_id, version_number);

-- 4. HISTORY TABLES: TEMPORAL (GiST) INDEXES
-- on the fly, GiST can mathematically cluster the historical timeline. 

CREATE INDEX idx_hist_branch_time 
ON insurance.company_branch_history 
USING GIST (branch_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_agent_time 
ON insurance.agent_history 
USING GIST (agent_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_customer_time 
ON insurance.customer_history 
USING GIST (customer_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_policy_time 
ON insurance.policy_history 
USING GIST (policy_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_payment_time 
ON insurance.payment_history 
USING GIST (payment_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_claim_time 
ON insurance.claim_history 
USING GIST (claim_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_cust_pol_time 
ON insurance.customer_policy_history 
USING GIST (customer_id, tsrange(valid_from, valid_to));

CREATE INDEX idx_hist_claim_pol_time 
ON insurance.claim_policy_history 
USING GIST (claim_id, tsrange(valid_from, valid_to));
